<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Sponsorship Opportunity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style type="text/css">
body {
  font-family: Arial, sans-serif;
}
    </style>
  </head>
  <body>
    Hello RGUHack Team,<br /><br/>
    My company and I are expressing interest in sponsoring RGUHack.<br />
    I am a <?php echo $job_title; ?> at <?php echo $company_name; ?>.<br />
    You can email me at <?php echo $email; ?>.<br />
    Give me a ring on <?php echo $telephone; ?>.<br />
    Visit our website <?php echo $website; ?>.<br /><br />
    Kind regards,<br />
    <?php echo $first_name; ?> <?php echo $last_name; ?>
  </body>
</html>
